### PR TITLE
Times and login screen css fix 

### LINKED ISSUE #82: Login screen styling
Fix the styling on the login screen in login.css

### LINKED ISSUE #84: Times css
There is a problem where the css for leaderboard overwrites the css for the times page, this needs to be fixed in order to be able to modify this page individually without either of them breaking.

### PR DESCRIPTION
**Pull request by klarasve**
Times has it's own css stylesheet and should no longer interfere with leaderboard css, it can therefore now be changed individually. Login css fixed (I hope?).

### CODE REVIEW

File: smartcar_frontend/src/components/times/Times.js [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+  // useEffect(() => {
+  //   fetch(TimeList)
+  //     .then((response) => response.json())
+  //     .then((users) => setUsers(users))
+  //     .catch((err) => console.error(err));
+  // }, []);
+
+  return (
+    <div>
+      <h2 className="times-heading">Leaderboard</h2>
```
Comment (VernitaJ) [inline smartcar_frontend/src/components/times/Times.js:17]: This is just dummy code that will be replaced with functional code in the next database PR.

**Review by VernitaJ — APPROVED** [review]
The styling is incorporated well into the application, and fixes the login as well as times component styling.
